generator:
    method:                         random
    parameters:
        count:                      10000

        shape:
            drag_coefficient:        
                distribution:       constant
                parameters:
                    value:          0.6                         # 0.6 for a spherical body
            shape_factor:           1.21                        # 1.21 for a spherical body

        material:
            density:                
                distribution:       'constant'
                parameters:
                    value:          625 
            heat_transfer:          1.0                         # Heat transfer coefficient, default 0.5
            ablation_heat:          6000000                     # Specific enthalpy of vaporization, in J/kg

        mass:
            distribution:           'pareto'                    # Particle mass distribution. Possible values 'pareto', 'exponential' or a number
            parameters:
                minimum:            0.000001                    # Minimum particle mass, in kg
                shape:              1.7                         # Shape of the distribution, corresponds to s index (N(m) \propto m^-s)

        position:
            distribution:           pillow                      # Name of the distribution, currently only 'pillow'
            parameters:
                south:              43                          # Southern bound, degrees of latitude
                north:              53                          # Northern bound, degrees of latitude
                west:               12                          # Western bound, degrees of longitude
                east:               24                          # Eastern bound, degrees of longitude
                bottom:             130000                      # Lower bound, metres above surface
                top:                150000                      # Upper bound, metres above surface

        velocity:
            distribution:           'shower'                    # Currently only 'shower'
            parameters:
                ra:                 43                          # Right ascension in degrees
                dec:                56                          # Declination in degrees
                speed:              59000                       # Entry speed in m/s

        time:
            distribution:           'uniform'
            parameters:
                begin:              2016-08-11T19:00:00         # Beginning of the interval, ISO8601
                end:                2016-08-12T02:00:00         # End of the interval, ISO8601

integrator:                                             
    name:                           'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                            20                          # Frames per second
    spf:                            1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
